# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
  terraform {
    backend "s3" {
      bucket         = "ups-infra-state"
      key            = "vpc/deployment/upswing-management/plus/terraform.tfstate"
      region         = "ap-south-1"
      encrypt        = true
      profile = "upswing-management"
      dynamodb_table = "ups-infra-state-lock-table"
      role_arn = "arn:aws:iam::776633114724:role/tf-state-manager"
    }
  }
