# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "ups-infra-state"
    key            = "vpc/deployment/Stage-Infra/plus/terraform.tfstate"
    region         = "ap-south-1"
    encrypt        = true
    role_arn = "arn:aws:iam::776633114724:role/tf-state-manager"
    session_name = "terraform"
    dynamodb_table = "ups-infra-state-lock-table"
  }
}
